export const AUDIT_LOAD = "AUDIT/LOAD";
export const AUDIT_LOAD_FAILED = "AUDIT/LOAD/FAILED";
export const AUDIT_LOAD_COMPLETE = "AUDIT/LOADED/COMPLETE";
export const AUDIT_SAVE_FAILED = "AUDIT/SAVE/FAILED"
export const AUDIT_SAVE_COMPLETE = "AUDIT/SAVE/COMPLETE";
