export const AUDIT_LOAD = "AUDIT/LOAD";
export const AUDIT_LOAD_FAILED = "AUDIT/LOAD/FAILED";
export const AUDIT_LOAD_COMPLETE = "AUDIT/LOADED/COMPLETE";
export const AUDIT_SAVE_FAILED = "AUDIT/SAVE/FAILED"
export const AUDIT_SAVE_COMPLETE = "AUDIT/SAVE/COMPLETE";
export const AUDIT_CLEAR = "AUDIT/CLEAR";
export const AUDIT_CLEAR_FAILED = "AUDIT/CLEAR/FAILED";
export const AUDIT_CLEAR_COMPLETE = "AUDIT/CLEAR/COMPLETE";