export const RECORDING_LOAD = "RECORDING/LOAD";
export const RECORDING_LOAD_FAILED = "RECORDING/LOAD/FAILED";
export const RECORDING_LOAD_COMPLETE = "RECORDING/LOADED/COMPLETE";
export const RECORDING_SAVE_FAILED = "RECORDING/SAVE/FAILED"
export const RECORDING_SAVE_COMPLETE = "RECORDING/SAVE/COMPLETE";
